<?php
return [

    'curso' => [
        'titulo'   => 'Cursos',
        'singular' => 'curso',
        'tabla'    => 'curso',
        'pk'       => 'id_curso',
        'orden'    => 'anio_escolar DESC, nombre',
        'listar'   => ['nombre', 'nivel', 'anio_escolar', 'cupo_maximo'],
        'buscar'   => ['nombre', 'nivel'],
        'campos'   => [
            'nombre'       => ['label' => 'Nombre del curso', 'tipo' => 'text', 'req' => true, 'max' => 50],
            'nivel'        => ['label' => 'Nivel', 'tipo' => 'enum', 'req' => true, 'opciones' => ['Preescolar', 'Primaria', 'Secundaria', 'Media']],
            'anio_escolar' => ['label' => 'Año escolar', 'tipo' => 'anio', 'req' => true],
            'cupo_maximo'  => ['label' => 'Cupo máximo', 'tipo' => 'numero', 'req' => true, 'ayuda' => 'Entre 1 y 25'],
        ],
    ],

    'acudiente' => [
        'titulo'   => 'Acudientes',
        'singular' => 'acudiente',
        'tabla'    => 'acudiente',
        'pk'       => 'id_acudiente',
        'orden'    => 'nombre',
        'listar'   => ['nombre', 'documento', 'parentesco', 'correo', 'direccion'],
        'buscar'   => ['nombre', 'documento', 'correo'],
        'campos'   => [
            'nombre'     => ['label' => 'Nombre completo', 'tipo' => 'text', 'req' => true, 'max' => 100],
            'documento'  => ['label' => 'Documento', 'tipo' => 'text', 'req' => true, 'max' => 20],
            'parentesco' => ['label' => 'Parentesco', 'tipo' => 'enum', 'req' => true, 'opciones' => ['Madre', 'Padre', 'Abuelo', 'Abuela', 'Tio', 'Tia', 'Hermano', 'Hermana', 'Otro']],
            'correo'     => ['label' => 'Correo', 'tipo' => 'text', 'max' => 100],
            'direccion'  => ['label' => 'Dirección', 'tipo' => 'text', 'max' => 150],
        ],
    ],

    'telefono' => [
        'titulo'            => 'Teléfonos',
        'singular'          => 'teléfono',
        'tabla'             => 'telefono_acudiente',
        'pk'                => ['id_acudiente', 'numero'],
        'solo_crear_borrar' => true,
        'orden'             => 'id_acudiente',
        'listar'            => ['id_acudiente', 'numero', 'tipo'],
        'buscar'            => ['numero'],
        'campos'            => [
            'id_acudiente' => ['label' => 'Acudiente', 'tipo' => 'fk', 'req' => true, 'tabla' => 'acudiente', 'valor' => 'id_acudiente', 'etiqueta' => 'nombre'],
            'numero'       => ['label' => 'Número', 'tipo' => 'text', 'req' => true, 'max' => 20, 'ayuda' => 'Entre 7 y 20 dígitos'],
            'tipo'         => ['label' => 'Tipo', 'tipo' => 'enum', 'req' => true, 'opciones' => ['celular', 'fijo', 'trabajo']],
        ],
    ],

    'estudiante' => [
        'titulo'   => 'Estudiantes',
        'singular' => 'estudiante',
        'tabla'    => 'estudiante',
        'pk'       => 'id_estudiante',
        'orden'    => 'nombre',
        'listar'   => ['nombre', 'documento', 'fecha_nacimiento', 'genero', 'id_acudiente', 'activo'],
        'buscar'   => ['nombre', 'documento'],
        'campos'   => [
            'nombre'           => ['label' => 'Nombre completo', 'tipo' => 'text', 'req' => true, 'max' => 100],
            'documento'        => ['label' => 'Documento', 'tipo' => 'text', 'req' => true, 'max' => 20],
            'fecha_nacimiento' => ['label' => 'Fecha de nacimiento', 'tipo' => 'fecha', 'req' => true],
            'genero'           => ['label' => 'Género', 'tipo' => 'enum', 'req' => true, 'opciones' => ['F', 'M', 'otro']],
            'id_acudiente'     => ['label' => 'Acudiente', 'tipo' => 'fk', 'req' => true, 'tabla' => 'acudiente', 'valor' => 'id_acudiente', 'etiqueta' => 'nombre'],
            'fecha_registro'   => ['label' => 'Fecha de registro', 'tipo' => 'fecha', 'req' => true],
            'activo'           => ['label' => 'Activo', 'tipo' => 'enum', 'req' => true, 'opciones' => ['1', '0'], 'ayuda' => '1 = activo, 0 = inactivo'],
        ],
    ],

    'matricula' => [
        'titulo'   => 'Matrículas',
        'singular' => 'matrícula',
        'tabla'    => 'matricula',
        'pk'       => 'id_matricula',
        'orden'    => 'fecha_matricula DESC',
        'listar'   => ['id_estudiante', 'id_curso', 'anio_escolar', 'fecha_matricula', 'estado'],
        'buscar'   => ['estado'],
        'campos'   => [
            'id_estudiante'   => ['label' => 'Estudiante', 'tipo' => 'fk', 'req' => true, 'tabla' => 'estudiante', 'valor' => 'id_estudiante', 'etiqueta' => 'nombre'],
            'id_curso'        => ['label' => 'Curso', 'tipo' => 'fk', 'req' => true, 'tabla' => 'curso', 'valor' => 'id_curso', 'etiqueta' => 'nombre'],
            'anio_escolar'    => ['label' => 'Año escolar', 'tipo' => 'anio', 'req' => true, 'ayuda' => 'Una sola matrícula por estudiante y año'],
            'fecha_matricula' => ['label' => 'Fecha de matrícula', 'tipo' => 'fecha', 'req' => true],
            'estado'          => ['label' => 'Estado', 'tipo' => 'enum', 'req' => true, 'opciones' => ['activa', 'retirada', 'culminada']],
        ],
    ],

    'profesor' => [
        'titulo'   => 'Profesores',
        'singular' => 'profesor',
        'tabla'    => 'profesor',
        'pk'       => 'id_profesor',
        'orden'    => 'nombre',
        'listar'   => ['nombre', 'documento', 'especialidad', 'id_supervisor'],
        'buscar'   => ['nombre', 'documento', 'especialidad'],
        'campos'   => [
            'nombre'        => ['label' => 'Nombre completo', 'tipo' => 'text', 'req' => true, 'max' => 100],
            'documento'     => ['label' => 'Documento', 'tipo' => 'text', 'req' => true, 'max' => 20],
            'especialidad'  => ['label' => 'Especialidad', 'tipo' => 'text', 'req' => true, 'max' => 80],
            'id_supervisor' => ['label' => 'Supervisor', 'tipo' => 'fk', 'tabla' => 'profesor', 'valor' => 'id_profesor', 'etiqueta' => 'nombre', 'ayuda' => 'Déjalo vacío si no tiene jefe de área'],
        ],
    ],

    'contrato' => [
        'titulo'   => 'Contratos',
        'singular' => 'contrato',
        'tabla'    => 'contrato_profesor',
        'pk'       => 'id_profesor',
        'orden'    => 'id_profesor',
        'listar'   => ['id_profesor', 'tipo_contrato', 'salario', 'fecha_inicio', 'fecha_fin'],
        'buscar'   => ['tipo_contrato'],
        'campos'   => [
            'id_profesor'   => ['label' => 'Profesor', 'tipo' => 'fk', 'req' => true, 'tabla' => 'profesor', 'valor' => 'id_profesor', 'etiqueta' => 'nombre', 'ayuda' => 'Un profesor solo puede tener un contrato'],
            'tipo_contrato' => ['label' => 'Tipo de contrato', 'tipo' => 'enum', 'req' => true, 'opciones' => ['planta', 'catedra', 'provisional']],
            'salario'       => ['label' => 'Salario', 'tipo' => 'numero', 'req' => true, 'ayuda' => 'Entre 1.000.000 y 20.000.000'],
            'fecha_inicio'  => ['label' => 'Fecha de inicio', 'tipo' => 'fecha', 'req' => true],
            'fecha_fin'     => ['label' => 'Fecha de fin', 'tipo' => 'fecha', 'ayuda' => 'Vacía si el contrato sigue vigente'],
        ],
    ],

    'asignatura' => [
        'titulo'   => 'Asignaturas',
        'singular' => 'asignatura',
        'tabla'    => 'asignatura',
        'pk'       => 'id_asignatura',
        'orden'    => 'codigo',
        'listar'   => ['codigo', 'nombre', 'creditos', 'intensidad_horaria', 'id_curso'],
        'buscar'   => ['codigo', 'nombre'],
        'campos'   => [
            'codigo'             => ['label' => 'Código', 'tipo' => 'text', 'req' => true, 'max' => 15],
            'nombre'             => ['label' => 'Nombre', 'tipo' => 'text', 'req' => true, 'max' => 80],
            'creditos'           => ['label' => 'Créditos', 'tipo' => 'numero', 'req' => true, 'ayuda' => 'Entre 1 y 10'],
            'intensidad_horaria' => ['label' => 'Intensidad horaria', 'tipo' => 'numero', 'req' => true, 'ayuda' => 'Horas semanales, entre 1 y 12'],
            'id_curso'           => ['label' => 'Curso', 'tipo' => 'fk', 'req' => true, 'tabla' => 'curso', 'valor' => 'id_curso', 'etiqueta' => 'nombre'],
        ],
    ],

    'asignacion' => [
        'titulo'            => 'Asignaturas por profesor',
        'singular'          => 'asignación',
        'tabla'             => 'asignatura_profesor',
        'pk'                => ['id_profesor', 'id_asignatura'],
        'solo_crear_borrar' => true,
        'orden'             => 'id_profesor',
        'listar'            => ['id_profesor', 'id_asignatura', 'fecha_asignacion'],
        'buscar'            => [],
        'campos'            => [
            'id_profesor'      => ['label' => 'Profesor', 'tipo' => 'fk', 'req' => true, 'tabla' => 'profesor', 'valor' => 'id_profesor', 'etiqueta' => 'nombre'],
            'id_asignatura'    => ['label' => 'Asignatura', 'tipo' => 'fk', 'req' => true, 'tabla' => 'asignatura', 'valor' => 'id_asignatura', 'etiqueta' => 'nombre'],
            'fecha_asignacion' => ['label' => 'Fecha de asignación', 'tipo' => 'fecha', 'req' => true],
        ],
    ],

    'nota' => [
        'titulo'   => 'Notas',
        'singular' => 'nota',
        'tabla'    => 'nota',
        'pk'       => 'id_nota',
        'orden'    => 'id_estudiante, periodo',
        'listar'   => ['id_estudiante', 'id_asignatura', 'periodo', 'valor', 'observacion'],
        'buscar'   => ['observacion'],
        'campos'   => [
            'id_estudiante' => ['label' => 'Estudiante', 'tipo' => 'fk', 'req' => true, 'tabla' => 'estudiante', 'valor' => 'id_estudiante', 'etiqueta' => 'nombre'],
            'id_asignatura' => ['label' => 'Asignatura', 'tipo' => 'fk', 'req' => true, 'tabla' => 'asignatura', 'valor' => 'id_asignatura', 'etiqueta' => 'nombre'],
            'periodo'       => ['label' => 'Periodo', 'tipo' => 'enum', 'req' => true, 'opciones' => ['1', '2', '3', '4']],
            'valor'         => ['label' => 'Nota', 'tipo' => 'text', 'req' => true, 'max' => 4, 'ayuda' => 'De 0.0 a 5.0, con punto'],
            'observacion'   => ['label' => 'Observación', 'tipo' => 'textarea', 'max' => 200],
        ],
    ],

    'asistencia' => [
        'titulo'   => 'Asistencia',
        'singular' => 'registro de asistencia',
        'tabla'    => 'asistencia',
        'pk'       => 'id_asistencia',
        'orden'    => 'fecha DESC',
        'listar'   => ['fecha', 'id_estudiante', 'id_asignatura', 'estado', 'observacion'],
        'buscar'   => ['estado', 'observacion'],
        'campos'   => [
            'id_estudiante' => ['label' => 'Estudiante', 'tipo' => 'fk', 'req' => true, 'tabla' => 'estudiante', 'valor' => 'id_estudiante', 'etiqueta' => 'nombre'],
            'id_asignatura' => ['label' => 'Asignatura', 'tipo' => 'fk', 'req' => true, 'tabla' => 'asignatura', 'valor' => 'id_asignatura', 'etiqueta' => 'nombre'],
            'fecha'         => ['label' => 'Fecha', 'tipo' => 'fecha', 'req' => true],
            'estado'        => ['label' => 'Estado', 'tipo' => 'enum', 'req' => true, 'opciones' => ['presente', 'ausente', 'tarde', 'excusa']],
            'observacion'   => ['label' => 'Observación', 'tipo' => 'textarea', 'max' => 200],
        ],
    ],

    'libro' => [
        'titulo'   => 'Libros',
        'singular' => 'libro',
        'tabla'    => 'libro',
        'pk'       => 'id_libro',
        'orden'    => 'titulo',
        'listar'   => ['isbn', 'titulo', 'autor', 'anio_publicacion', 'ejemplares', 'disponibles'],
        'buscar'   => ['isbn', 'titulo', 'autor'],
        'campos'   => [
            'isbn'             => ['label' => 'ISBN', 'tipo' => 'text', 'req' => true, 'max' => 20],
            'titulo'           => ['label' => 'Título', 'tipo' => 'text', 'req' => true, 'max' => 150],
            'autor'            => ['label' => 'Autor', 'tipo' => 'text', 'req' => true, 'max' => 100],
            'anio_publicacion' => ['label' => 'Año de publicación', 'tipo' => 'numero'],
            'ejemplares'       => ['label' => 'Ejemplares', 'tipo' => 'numero', 'req' => true],
            'disponibles'      => ['label' => 'Disponibles', 'tipo' => 'numero', 'req' => true, 'ayuda' => 'Nunca mayor que los ejemplares'],
        ],
    ],

    'prestamo' => [
        'titulo'   => 'Préstamos',
        'singular' => 'préstamo',
        'tabla'    => 'prestamo',
        'pk'       => 'id_prestamo',
        'orden'    => 'fecha_prestamo DESC',
        'listar'   => ['id_libro', 'id_estudiante', 'fecha_prestamo', 'fecha_devolucion', 'estado'],
        'buscar'   => ['estado'],
        'campos'   => [
            'id_libro'         => ['label' => 'Libro', 'tipo' => 'fk', 'req' => true, 'tabla' => 'libro', 'valor' => 'id_libro', 'etiqueta' => 'titulo'],
            'id_estudiante'    => ['label' => 'Estudiante', 'tipo' => 'fk', 'req' => true, 'tabla' => 'estudiante', 'valor' => 'id_estudiante', 'etiqueta' => 'nombre'],
            'fecha_prestamo'   => ['label' => 'Fecha del préstamo', 'tipo' => 'fecha', 'req' => true],
            'fecha_devolucion' => ['label' => 'Fecha de devolución', 'tipo' => 'fecha', 'ayuda' => 'Vacía si el libro sigue prestado'],
            'estado'           => ['label' => 'Estado', 'tipo' => 'enum', 'req' => true, 'opciones' => ['activo', 'devuelto', 'vencido']],
        ],
    ],

    'auditoria' => [
        'titulo'       => 'Auditoría',
        'singular'     => 'registro de auditoría',
        'tabla'        => 'auditoria',
        'pk'           => 'id_auditoria',
        'solo_lectura' => true,
        'orden'        => 'fecha_hora DESC',
        'listar'       => ['fecha_hora', 'tabla_afectada', 'operacion', 'id_registro', 'usuario_bd'],
        'buscar'       => ['tabla_afectada', 'operacion', 'usuario_bd'],
        'campos'       => [
            'fecha_hora'         => ['label' => 'Fecha y hora', 'tipo' => 'text'],
            'tabla_afectada'     => ['label' => 'Tabla afectada', 'tipo' => 'text'],
            'operacion'          => ['label' => 'Operación', 'tipo' => 'text'],
            'id_registro'        => ['label' => 'ID del registro', 'tipo' => 'numero'],
            'valores_anteriores' => ['label' => 'Valores anteriores', 'tipo' => 'textarea'],
            'valores_nuevos'     => ['label' => 'Valores nuevos', 'tipo' => 'textarea'],
            'usuario_bd'         => ['label' => 'Usuario', 'tipo' => 'text'],
        ],
    ],

];
